// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpbz1MWgLIJejeG7aR3D2mmXPCkte9u4',
    appId: '1:828877990239:web:c2e9b03eda6f52526d6eea',
    messagingSenderId: '828877990239',
    projectId: 'mess-91153',
    authDomain: 'mess-91153.firebaseapp.com',
    storageBucket: 'mess-91153.appspot.com',
    measurementId: 'G-Z4Y4E2DBST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Bv5wXR-xVGWMLXUhLLV--qzLEcAHMWw',
    appId: '1:828877990239:android:25f7583fb0eb4d586d6eea',
    messagingSenderId: '828877990239',
    projectId: 'mess-91153',
    storageBucket: 'mess-91153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCevaSsIQbHzSUcLuWJFcWKF-sIPf9fHHA',
    appId: '1:828877990239:ios:01cd0ee73c3eae956d6eea',
    messagingSenderId: '828877990239',
    projectId: 'mess-91153',
    storageBucket: 'mess-91153.appspot.com',
    iosClientId: '828877990239-m302bl2dvpq8bc2gssad2pqukm2ghjm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCevaSsIQbHzSUcLuWJFcWKF-sIPf9fHHA',
    appId: '1:828877990239:ios:3a1357b1bda932ba6d6eea',
    messagingSenderId: '828877990239',
    projectId: 'mess-91153',
    storageBucket: 'mess-91153.appspot.com',
    iosClientId: '828877990239-mk2ap9aq08bfrakevv80u68qsb0kjldb.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger.RunnerTests',
  );
}
